pub const SPEC035_MEDIA_SAFE_SUMMARY_MAX_CHARS: usize = 240;
pub const SPEC035_MEDIA_OWNER_REF_MAX_CHARS: usize = 160;
pub const SPEC035_MEDIA_OPAQUE_REF_MAX_CHARS: usize = 160;
pub const SPEC035_MEDIA_DIGEST_CHARS: usize = 71;
pub const SPEC035_MEDIA_OWNER_FACTS_MAX: usize = 5;
pub const SPEC035_MEDIA_UNAVAILABLE_REASONS_MAX: usize = 10;
pub const SPEC035_MEDIA_APPLIED_ADAPTERS_MAX: usize = 7;
pub const SPEC035_MEDIA_DISCLOSURE_SURFACES_MAX: usize = 5;
