[package]
name = "shacs-channels"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shacs-command = { path = "../shacs-command" }
shacs-projection = { path = "../shacs-projection" }
